name: Docker Build CI

on:
  schedule:
    - cron:  '0 9 * * *'

  push:
    # Run `master` as Docker `latest` image.
    branches: [ master ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build mbtiles
      env:
        db_user: ${{ secrets.db_user }}
        db_password: ${{ secrets.db_password }}
        db_host: ${{ secrets.db_host }}
        db_port: ${{ secrets.db_port }}
        db_name: ${{ secrets.db_name }}
      run: docker-compose up
    - name: Push mbtiles to github
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        git config --global user.name "nawasco+githubci"
        git config --global user.email "nawasco+githubci@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${NODE_AUTH_TOKEN}@github.com/nawasco/vt.git
        git add .
        git commit -m "update vectortiles"
        git push origin master
