name: Docker Build & Deploy

on:
  schedule:
    - cron:  '0 9 * * *'

  push:
    # Run `master` as Docker `latest` image.
    branches: [ master ]


jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build mbtiles
      env:
        db_user: ${{ secrets.DB_USER }}
        db_password: ${{ secrets.DB_PASSWORD }}
        db_host: ${{ secrets.DB_HOST }}
        db_port: ${{ secrets.DB_PORT }}
        db_name: ${{ secrets.DB_NAME }}
      run: docker-compose up
    - name: Push mbtiles to github
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        git config --global user.name "nawasco+githubci"
        git config --global user.email "nawasco+githubci@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${NODE_AUTH_TOKEN}@github.com/nawasco/vt.git
        git add .
        git commit -m "update vectortiles"
        git push origin master

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: npm run extract
    - name: configure git and deploy
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        git config --global user.name "nawasco+githubci"
        git config --global user.email "nawasco+githubci@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${NODE_AUTH_TOKEN}@github.com/nawasco/vt.git
        npm run deploy
